name: Env Example

on: push

env:
  APP_NAME: my-app
  Name: Laxmikanta

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: print the app
        run: |
         echo "This is the app $APP_NAME"
         echo "My name is $Name"
  demo-githubEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Use version
        run: echo "Version is $VERSION"
  demo-githubOutput:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: step1
        run: echo "status=success" >> $GITHUB_OUTPUT

      - name: Use output
        run: echo "Result is ${{ steps.step1.outputs.status }}"
  secret:
    runs-on: ubuntu-latest
    steps:
        - name: fetching secrets
          run: echo "This is the secret ${{secrets.DB_PASS}}"
  demo-region:
    runs-on: ubuntu-lates
    steps:
      - name: trying variable
        run : echo "deploying in ${{vars.region}}"